### ISSUE TITLE
Name of the mapping template jar file

### ISSUE THREAD

**Issue by AuPath** [cefriel/mapping-template#12]
Currently, the mapping-template JAR file follows the 'mapping-template-x.y.z' naming convention. This means that whenever a new version of the mapping-template is released, existing scripts integrating it require modification, even if there are no functional changes. Similarly, building the mapping-template via a Dockerfile (#9) presents challenges, as the resulting JAR file must be referenced by its version, necessitating Dockerfile updates for each release.

To simplify, I propose renaming it to 'mapping-template.jar' or 'mapt.jar' to ease command line usage. The version of the mapping-template.jar file should instead be exposed by a `--version` flag. @marioscrock, what do you think?

**Comment by marioscrock** [comment]
I agree with adding a `--version` flag, but I think it is preferable to force the user to rename the JAR instead of making it versionless (see also [link](https://stackoverflow.com/questions/16482102/when-should-a-jar-file-name-have-a-version-number-in-it-what-are-the-pros-and-c)).

Regarding the Dockerfile, we can use a "wildcard" when referencing the JAR (e.g., see [link](https://github.com/RMLio/rmlmapper-java/blob/master/Dockerfile)).
