### ISSUE TITLE
input format parameter when using a SQL db

### ISSUE THREAD

**Issue by AuPath** [cefriel/mapping-template#20]
The input format in this case is either "mysql" or "postgresql". These are not really input formats per se, would it perhaps make more sense to have a separate `--db-type` parameter that is only used when connecting to dbs?

**Comment by marioscrock** [comment]
Not sure, I think it overcomplicates the config. The "input format" selects the `Reader`, maybe we can change the name of the option but I would keep "mysql" and "postgresql" with the others. I left it like this because for `rdf` the input format is always the same but if a remote address is provided the connection is performed to the remote triplestore.
